# from http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxypass
RewriteEngine On

RewriteCond %{HTTPS} =off
RewriteRule . - [E=protocol:http,E=port:80]
RewriteCond %{HTTPS} =on
RewriteRule . - [E=protocol:https,E=port:443]

SSLProxyEngine on
SSLProxyVerify none 
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off
ProxyPreserveHost On
ProxyPassReverse / https://1.2.3.4:443/
ProxyPass / https://1.2.3.4:443/
ServerName kerio.precursor.ca

