# from http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxypass
RewriteEngine On

RewriteCond %{HTTPS} =off
RewriteRule . - [E=protocol:http,E=port:80]
RewriteCond %{HTTPS} =on
RewriteRule . - [E=protocol:https,E=port:443]

ProxyPreserveHost On
ProxyPassReverse / http://1.2.3.4:80/
ProxyPass / http://1.2.3.4:80/
ServerName kerio.precursor.ca