# from http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxypass
RewriteEngine On

RewriteCond %{HTTPS} =off
RewriteRule . - [E=protocol:http,E=port:8000]
RewriteCond %{HTTPS} =on
RewriteRule . - [E=protocol:https,E=port:8010]

SSLProxyEngine on
ProxyPassReverse / https://rumpus.precursor.ca:8010/
ProxyPass / https://rumpus.precursor.ca:8010/
