# from http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxypass
RewriteEngine On

RewriteCond %{HTTPS} =off
RewriteRule . - [E=protocol:http,E=port:8001]
RewriteCond %{HTTPS} =on
RewriteRule . - [E=protocol:https,E=port:8011]

SSLProxyEngine on
# This version is for FileMaker 15
# If using FileMaker Server 12 - 14 you should uncomment the commented lines below:
# RewriteRule ^/fmi/(.*) %{ENV:protocol}://localhost:%{ENV:port}/fmi/$1 [P]
ProxyPassReverse / https://filemaker.precursor.ca:8011/
#ProxyPassReverse  /fmi/ http://localhost/fmi/
#ProxyPassReverse  /fmi/ https://localhost/fmi/

ProxyPass / https://filemaker.precursor.ca:8011/
ProxyPass /admin-console http://localhost:16001/admin-console
ProxyPass /admin-console/ http://localhost:16001/admin-console/
ProxyPassReverse /admin-console/ http://localhost:16001/admin-console/
