# from http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxypass
RewriteEngine On

RewriteCond %{HTTPS} =off
RewriteRule . - [E=protocol:http,E=port:8003]
RewriteCond %{HTTPS} =on
RewriteRule . - [E=protocol:https,E=port:8013]

SSLProxyEngine on
ProxyPassReverse / https://kerio.precursor.ca:8013/
ProxyPass / https://kerio.precursor.ca:8013/
